# Question 1 - What version of pandas is it?

In [31]:
import pandas as pd
print("We are using Pandas version ... ", pd.__version__)

We are using Pandas version ...  2.0.3


# Question 2 - How many columns are in the dataset?

In [67]:
df = pd.read_csv("housing.csv")
print("There are ", len(df.columns), "columns")

There are  10 columns


# Question 3 - Which columns in the dataset have missing values?

In [33]:
a = df.isna().sum()
a_idx = a > 0
NaN_a = a[a_idx]
print (NaN_a)

total_bedrooms    207
dtype: int64


# Question 4 - How many unique values does the ocean_proximity column have?

In [34]:
a = df['ocean_proximity'].unique()
print(len(a)," unique values")

5  unique values


# Question 5 - What's the average value of the median_house_value for the houses located near the bay?

In [35]:
print(df.columns)
df_NearBay = df[df['ocean_proximity'] == 'NEAR BAY']
print(df_NearBay['median_house_value'].mean())

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')
259212.31179039303


# Question 6
* Calculate the average of total_bedrooms column in the dataset.
* Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
* Now, calculate the average of total_bedrooms again.
* Has it changed?

In [36]:
# Calculate average number of bedrooms
Av_Total_Bedrooms = df['total_bedrooms'].mean()
print("Average total number of bedrooms: ", Av_Total_Bedrooms)

# Replace values
df['total_bedrooms'] = df['total_bedrooms'].fillna(Av_Total_Bedrooms)

# Calculate new mean 
Av_Total_Bedrooms2 = df['total_bedrooms'].mean()
print("New average total number of bedrooms: ", Av_Total_Bedrooms2)

#Print difference
print(Av_Total_Bedrooms - Av_Total_Bedrooms2)


Average total number of bedrooms:  537.8705525375618
New average total number of bedrooms:  537.8705525375617
1.1368683772161603e-13


# Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

In [84]:
import numpy as np

# Select all the options located on Islands
df_Islands = df[df['ocean_proximity'] == 'ISLAND']

# Select only columns: housing_median_age, total_rooms, and total_bedrooms
df_Islands_F = df_Islands[['housing_median_age','total_rooms','total_bedrooms']]
print(df_Islands_F)

# Convert to numpy array X
X = df_Islands_F.to_numpy()
print('\n',X,'\n')

# Matrix-Matrix multiplication between X and its transpose(XT) to get XTX
XT = X.T
print("Transpose of X :\n",XT,'\n')

XTX = XT.dot(X)
print('XTX is \n',XTX,'\n')

# Compute the inverse of XTX
iXTX = np.linalg.inv(XTX)
print ('XTX inverse: \n',iXTX,'\n')

# Create an array y with values [950, 1300, 800, 1000, 1300]
y = np.array([950, 1300, 800, 1000, 1300])
print('y values: ',y)

# Multiply the inverse of XTX with the transpose of X and then multiply the result by y. Call this w
v = iXTX.dot(XT)
w = v.dot(y)

print(w)

# What's the value of the last element in w?
print(w[-1])

      housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

 [[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]] 

Transpose of X :
 [[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]] 

XTX is 
 [[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]] 

XTX inverse: 
 [[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]] 

y values:  [ 950 1300  800 1000 1300]
[23.12330961 -1.48124183  5.69922946]
5.699229455065565
